<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-08-27 09:52

$extensionPath = t3lib_extMgm::extPath('tmpl');
return array(
	'tx_tmpl_languagefileunavailableexception' => $extensionPath . 'classes/exceptions/class.tx_tmpl_languagefileunavailableexception.php',
	'tx_tmpl_nogetterexception' => $extensionPath . 'exceptions/class.tx_tmpl_nogetterexception.php',
	'tx_tmpl_testcase' => $extensionPath . 'tests/class.tx_tmpl_testcase.php',
	'tx_tmpl_viewhelper_nl2br_testcase' => $extensionPath . 'tests/class.tx_tmpl_viewhelper_Nl2br_testcase.php',
	'tx_tmpl_viewhelper_crop_testcase' => $extensionPath . 'tests/class.tx_tmpl_viewhelper_crop_testcase.php',
	'tx_tmpl_viewhelper_date_testcase' => $extensionPath . 'tests/class.tx_tmpl_viewhelper_date_testcase.php',
	'tx_tmpl_viewhelper_getcobj_testcase' => $extensionPath . 'tests/class.tx_tmpl_viewhelper_getcobj_testcase.php',
	'tx_tmpl_viewhelper_lll_testcase' => $extensionPath . 'tests/class.tx_tmpl_viewhelper_lll_testcase.php',
	'tx_tmpl_viewhelper_oddeven_testcase' => $extensionPath . 'tests/class.tx_tmpl_viewhelper_oddEven_testcase.php',
	'tx_tmpl_viewhelper_ts_testcase' => $extensionPath . 'tests/class.tx_tmpl_viewhelper_ts_testcase.php',
	'tx_tmpl_viewhelper' => $extensionPath . 'interfaces/interface.tx_tmpl_viewhelper.php',
	'tx_tmpl_viewhelperprovider' => $extensionPath . 'interfaces/interface.tx_tmpl_viewhelperprovider.php',
	'tx_tmpl_template' => $extensionPath . 'classes/class.tx_tmpl_template.php',
	'tx_tmpl_viewhelper_crop' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_crop.php',
	'tx_tmpl_viewhelper_date' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_date.php',
	'tx_tmpl_viewhelper_getcobj' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_getcobj.php',
	'tx_tmpl_viewhelper_ifelse' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_ifelse.php',
	'tx_tmpl_viewhelper_ifequals' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_ifequals.php',
	'tx_tmpl_viewhelper_image' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_image.php',
	'tx_tmpl_viewhelper_link' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_link.php',
	'tx_tmpl_viewhelper_lll' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_lll.php',
	'tx_tmpl_viewhelper_nl2br' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_nl2br.php',
	'tx_tmpl_viewhelper_oddeven' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_oddeven.php',
	'tx_tmpl_viewhelper_ts' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_ts.php',
	'tx_tmpl_viewhelper_url' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_url.php',
	'tx_tmpl_viewhelper_urlencode' => $extensionPath . 'classes/viewhelper/class.tx_tmpl_viewhelper_urlencode.php',
);
?>